### ISSUE TITLE
Order in passing parameters.

### ISSUE THREAD

**Issue by stepan-tsirkin** [wannier-berri/wannier-berri#125]
The number of parameters that we use in calculation is growing, and we are now using a complicated system to determine which parameters shopuld be passed where. I feel that it is becoming a mess now, both in terms of further implementation and in terms of documentation.

We now have `parameters_K`, `parameters` and `specific_parameters`, and also `quantities` and `user_quantities` . 

I suggest a different scheme. Namely, we will have no pre-defined `quantities`. Instead all calculators will be passed as a sictionary `{'key':calculator}` (similar to `user_quantities`), where `calculator` accepts a single  parameter `data_K`, and nothing more. 

Our pre-defined calculators will be functions of more parameters, so the user before running a calculation has to reduce their number using `functools.partial`. All parameters should be documented in the docstring of the calculator (common parameters may be documented in the docstring of the corresponding module, to avoid multiple repeating of the same). 

In my view, this will make it clearer (both for the user and developer), which parameters go where, and allow 

Explicitly to `integrate` or `tabulate` we should pass only parameters that have to be common for all quantities , such as `grid`, refinement options, `parameters_K` .  even `Efermi` and `omega` should not be passed explicitly to `integrate`

What do you think of this? Do you see any drawbacks of such approach?

**Comment by jaemolihm** [comment]
I strongly agree that the input parameters needs some cleanup. I think what you propose is a good solution. Everything becomes a `Calculator`, so the problem are divided into two smaller pieces (setting up a `Calculator` with proper arguments, and then `run`-ning a calculation).

One possible drawback that come to my mind is that the input argument can be somewhat complicated. Of course, the current situation is also complicated, so changing it is needed. But the following seems a bit too verbose, compared to the current interface `integrate(quantities=["ahc"], ...)` and `tabulate(quantities=["Berry"], ibands=np.arange(4, 10), ...)`. Maybe we can provide a utility that looks like the previous `__integrate` and `__tabulate` interface with minimal, widely (but not always) used arguments (e.g. `tetra`) and returns `calculators` dictionary, so that users who just want simple, well-known quantities (e.g. AHC, Berry dipole, spin Hall, shift current, energy) can just use them? (Something like `get_calculators_with_old_style_syntax(integrate_quantities=["ahc"], tetra=True)` (name should be changed...))
```python
                "ahc_calc":wberri.calculators.AHC(Efermi,tetra=True),
                 "tabulate":wberri.calculators.TabulatorAll({
                            "Energy":wberri.calculators.Energy(),
                            "berry":wberri.calculators.BerryCurvature(),
                                  }, 
                                       ibands = np.arange(4,10))
                          }, 
```

**Comment by stepan-tsirkin** [comment]
Thank you for the comment @jaemolihm 

Well, the verbosity becomes less if we do `import wannierberri.calculators as calc`. Also for common parameters one may use a dictionary and pass it as `**kwargs`. 

Also, combinintg tabulating calculators into `TabulatorAll` is a temporary solution, I will think later how to avoid it. 

I think your concerns are about those users that are used to the separation between a (compiled) "code" and "input files". But it is 2022, so we do not need to stick 

Yes, we can make another version like `run_simple(system,grid,quantities = [],**parameters)`, but 

1. it will be a pain to maintain it (when we change some parameters in calculators, we will takecare to update that part manually
2. because of (1) it will always have  a limited functionality. therefore, it may be concidered a "trial version" for newcomers, to get them hooked. 
3. It will need a repeated documentation.

Anyway, so far I am not removing the old interface (becuase it works!), but I do not feel like maintaining it for long either.  Do you wish to take this responsibility, to maintain a "simple interface"?

**Comment by jaemolihm** [comment]
I also do think that we do not need and do not want to stick to the dichotomy of code and input files.

I agree that a separate function like `run_simple` is a pain to maintain and think we should not have such a thing. I will wait until your new interface get finalized and make more concrete suggestions as a PR (if I think one is needed) .
