### ISSUE TITLE
the error for wannier90.spn created by vaspspn.py

### ISSUE THREAD

**Issue by hahArcher1** [wannier-berri/wannier-berri#182]
hello developers, I use the vaspspn.py to get wannier90.spn file from WAVECAR. But the  wannier90.spn I get, can not be used in wannier90 code for calculating SHC. The error is "Reading spin matrices from wannier90.spn in get_SS_R : Created from wavecar at 2022-05-29T16:40:07.650747
 Exiting.......
 wannier90.spn has wrong number of k-points"

Thank you very much!

**Comment by stepan-tsirkin** [comment]
Most probably this is because your WAVECAR contains only the irreducible kpoints, while all kpoints are needed to be present in the spn file. vaspspn.py does not perform symmetry operations to unfold on the full BZ. Do a non-selfconsistent calculation on the full BZ (`ISYM=-1`) to get all files consistently in one run This is anyway [recommended](https://www.wanniertools.org/tutorials/high-quality-wfs/) :

>**Special for VASP user**:
>If you are going to construct WFs for a system with SOC, then Please set “`ISYM=-1`” in the INCAR file if “`LWANNIER90 = T`” is present. Since there are some bugs in copying spinor wave functions from one k point to the one related by symmetry in VASP, then the quality of WFs would be significantly improved after we turn off this symmetry tag.

Also note, that a better [solution](https://github.com/Chengcheng-Xiao/VASP2WAN90_v2_fix) is offered by @Chengcheng-Xiao , which also hopefully will appear in future versions of VASP
