### ISSUE TITLE
AHC value 10x large since version 0.13

### ISSUE THREAD

**Issue by AbhirupRK** [wannier-berri/wannier-berri#219]
There is some issue with factor of 100 when calculating AHC. Kindly fix it. Till then sticking to version 0.12.

**Comment by stepan-tsirkin** [comment]
It is not a bug, it's a feature.

We decided to convert everything to SI units, so AHC is in S/m instead of S/cm, therefore the factor of 100

The units are generally written in the top of the output .dat file.

**Comment by stepan-tsirkin** [comment]
@AbhirupRK , the output now looks like this
![image](https://user-images.githubusercontent.com/22172977/207850775-85155a6d-d277-4398-b1f7-2f073ba91fb7.png)

quite descriptive, although one needs to render latex  by eyes :)  Ayway, the rendered is in the [documentation](https://wannier-berri.org/docs/calculators.html#wannierberri.calculators.static.AHC) 

Make sure you use the new interface with the [run()](https://wannier-berri.org/docs/run.html#running-a-calculation) instead of `integrate()`. Please see [tutorial](https://wannier-berri.org/tutorials/basic/tutorial-wb-basic.html#Tutorial-on-Wannier-Berri-:-interpolating-bands,-Berry-curvatures,-and-integrating-them) for clarification.

**Comment by AbhirupRK** [comment]
Thanks for the detailed comment @stepan-tsirkin. I was running with old `integrate()` method initially. The updated tutorial (including DIY) clarified all the confusions. 

I have one question though. Suppose I was to change the weight function in AHC formula altogether to say, log(f). Is there any shortcut? Even if not, can you guide me where to look for in the code?
