### ISSUE TITLE
Generating and Using uHu files

### ISSUE THREAD

**Issue by alisufyan15** [wannier-berri/wannier-berri#253]
I generated uHu file from wannier90 output via the following command and for wannier90.win input
python -m wannierberri.utils.mmn2uHu wannier90  targets=uHu

```
num_wann        = 128
num_bands       = 128
exclude_bands   = 1-48   
spinors         = T
begin projections
Nb:d
Co:d
Te:p
end projections
num_iter        = 1      
dis_num_iter    = 1  
```     

However, in the calculation of Orbital magnetization using wannier90, it gives an error "wannier90.uHu has not the right number of bands"
May I ask how can I resolve this issue? Is it because I excluded some bands?
Also, It would be extremely useful if you share how can I calculate orbital magnetization using wannier-berri package?
Thanks in advance.

**Comment by stepan-tsirkin** [comment]
For calculations of orbital magnetization check the tutorial 
https://wannier-berri.org/tutorials/basic/tutorial-wb-basic.html#Integration-on-a-grid:-anomalous-Hall-conductivity
and use the following calculator
https://wannier-berri.org/docs/calculators.html#wannierberri.calculators.static.Morb

**Comment by shahid-sattar** [comment]
Dera Stepan, thanks for the response; May I ask something relevant here about orbital magnetization (OM) computation:

I am trying to compute OM for a 2L MnBi2Te4. The net magnetization is zero in vasp output but OM is coming out to be non-zero.
In vasp, I have NBANDS=168 and 
In wannierzation, I did 
exclude_bands   = 1-76
num_bands = 92
num_wann = 92

wannierzation is very nice, DFT and w90 gives excellent match. First 76 bands from vasp are exculded and out of remaining 92 bands, 58 are occupied and 32 are unoccupied.
For OB part, I generated uHu file using wannier-berri by the following command:
**python -m wannierberri.utils.mmn2uHu wannier90  targets=uHu**
which gives a message that "**uHu from mmn red to 92 sum 92 bnd 2023-07-19T16:31:49.896478**"
Now the output gives non-zero magnetization:
 M_orb (bohr magn/cell)        x          y          z
 ======================      0.2133     0.1535     0.0704

What I mainly want to ask is about the generation and inclusion of bands in the step of wannier-berri. As you mentioned above, do you think excluding bands from below (1-76) and also not using considerably more bands then Wannier functions is the main reason here? 
Can you comment if I should take only the occupied bands (58) in generating uHu files or all bands (92)?
Thanks in advance.

**Comment by shahid-sattar** [comment]
@stepan-tsirkin would you like to share your thoughts about this issue?

**Comment by stepan-tsirkin** [comment]
@shahid-sattar  , I have many thoughts

If the net magnetization is zero in VASP, it must be not accidental, but due to some symmetry (Inversion*TimeReversal, or other)  . Orbital magnetization transforms under symmetry operations in the same way as the spin magnetization, therefore it should also come out zero, when the calculation is "good"

>  is the main reason here?

A reason of what? I guess, you mean the reason you get a nonzero value. 

## constructing good WFs 

There may be a number of reason. First, WFs very often break the symmetries numericall (slightly or severely) even when the band energies match. symmetry-adapted WFs are not available with VASP. So, one needs to choose initial projections for WFs carefully.  Then, check the resulting spreads and centers of WFs - do they respect the symmetry. If they break symmetries just slightly, consider applying the symmetrization procedure : https://docs.wannier-berri.org/en/master/docs/system.html#symmetrization-of-the-system


Choosing the same number of WFs as number of bands almost always leads to badly asymmetric WFs. You need considerably more bands then WFs, to do a proper disentanglement. 

Constructing WF for valence bands only is an option, but sometimes tricky, and impossible is bands are topological. 



A good brief guide on construction of good WFs  was written by @quanshengwu here:  https://www.wanniertools.org/tutorials/high-quality-wfs/


## computing orbital magnetization:

Your output of M_orb is from Wanier90 . Did you use the `use_ws_distance` parameter?  Did you try to calculate the same with WannierBerri? did they match?



## generating uHu
Regarding your procedure of generating uHu, although I suspect it is not the main source of errors, I suggest the following for a rigorous calculation:

1. Never exclude lowere (semicore) bands from summation
2. include all bands that you have in ab initio calculation
3. check if you need  to include more bands in the VASP step (if you can afford it)

So, smth like 

```
python3 -m wannierberri.utils.mmn2uHu seedname IBstart=77 NBout=92 NBsum=168  targets=mmn,uHu,eig,amn
```

Note: you should not `exclude_bands` while generating the mmn and eog files in VASP

## final goal

But if your final goal is to compute orbital magnetization for a crystal that has **exactly** zero spin magnetization, you will anyway get a zero orbital one.

**Comment by shahid-sattar** [comment]
@stepan-tsirkin I really appreciate your detailed response. 
I will consider your valuable feedback and will update this thread soon.
