### ISSUE TITLE
How to calculate Berry curvature dipole value for 2D system i.e, along xz and yz component 

### ISSUE THREAD

**Issue by SaranshaM** [wannier-berri/wannier-berri#336]
Respected Sir, 

I was evaluating Berry curvature dipole (BCD) for a 2D system, for which reported literature suggests the components contributing to finite  BCD are primarily xz znd yz components. Since the example contains xx,yy, zz components, i request your kind help on how i can access the xz , yz or any other component from file produced. 
![BCD_component](https://github.com/wannier-berri/wannier-berri/assets/133223443/61872c91-d159-4f21-942a-8509ac34ebe7)

I sincerely appreciate your kind assistance.
Best regards
Saransha Mohanty

**Comment by stepan-tsirkin** [comment]
In this example,  xz component will be in the `data_fsea[:,0,2]` and the yz in `data_fsea[:,1,2]`

Note, that some other components (xx,yy,xy) are also allowed in quasi-2d systems (actually, almost any real system, because it has a finite thickness).  This is because the Berry connection in the confined direction becomes the position operator.   But the zx, zy and zz should be zero, because there is no band gradient (or Berry curvature gradient) in the z direction.

Also note that for better precision on 2d and quasi-2d systems it is advised to use System(..., periodic=[True,True,False])

**Comment by SaranshaM** [comment]
Thank you very much Sir. And Sir, for 2d systems whose inputs are imported from wannier90 in the system=wberri.System_w90(...), should we use the periodic=[True,True,false] ? When i do that, i am encountering the syntax error as follows 
![system_w90](https://github.com/wannier-berri/wannier-berri/assets/133223443/6556e806-f961-42d6-82b5-490f938b863a).

**Comment by stepan-tsirkin** [comment]
you just forgot a comma after use_wcc_phase=True

**Comment by SaranshaM** [comment]
Thank You Sir. Its working. 
Best regards,
Saransha

**Comment by SaranshaM** [comment]
Respected Sir, 
Sir i was calculating berry curvature along the high symmetry points as shown in attached figure. I wanted to plot the colorbar of the magnitude of BC along with figure. I couldn't find the data set from which the graph is plotted. I used the following lines in # plot the Berry curvature as given in the example
 path_result.plot_path_fat( path,
              quantity='berry',
              component='z',
              save_file="ab_bands+berry.pdf",
              Eshift=1.9193,
              Emin=-3,  Emax=2,
              iband=None,
              mode="fatband",
              fatfactor=4,
              cut_k=False, 
              close_fig=True,
              show_fig=True
              )
Sir, is there any particular line to be added here so that the colorbar will appear simultaneously along with the figure ?
![color bar berry curvature](https://github.com/wannier-berri/wannier-berri/assets/133223443/845cb298-05c2-47b7-a949-813b3795f324)

Looking forward to your kind guidance.
Warm regards
Saransha

**Comment by stepan-tsirkin** [comment]
There is no actual colorbar here because the color just denotes the sign of the Berry curvature, while the magnitude is expressed by the size of the dots, according to these lines:

https://github.com/wannier-berri/wannier-berri/blob/5bfe6bd4151fa52656fb357616936aa4b290dcb5/wannierberri/result/__tabresult.py#L275-L278

If you want to plot it color-coded, you need to modify the plotting script to your taste.

**Comment by SaranshaM** [comment]
Okay Sir, Thanks for the helpful advice! 
Warm regards
Saransha

**Comment by SaranshaM** [comment]
Respected Sir, 
Sir one more question. In the plot Berry curvature dipole, the energy level labeled as 'Fermi level' , is the '0' value corresponds to E-EF (by default)  or we need to subtract EF from scf.out file for correct figure of BCD. I am little confused in this regard.
![fermi level](https://github.com/wannier-berri/wannier-berri/assets/133223443/d4f43af0-3643-4eb8-9e26-3a086b1423f0)

Looking forward to your kind response.
Best regards
Saransha

**Comment by stepan-tsirkin** [comment]
By default Fermi level is not subtracted, so you need to take it either from the scf.out file, of calculate from the cumDOS curve (the point where the number of electrons per unit cell reaches the correct value).

**Comment by SaranshaM** [comment]
Thank you sir the comment, sir do we need to multiply the BCD component with the system's lattice constant value for plotting ? in angstrom , is it correct ?

**Comment by stepan-tsirkin** [comment]
For 3D system berry dipole is dimensionless, but for 2D it has the units of length, therefore you need to multiply by the lattice period (of the slab geometry) in the third direction. In any units you like, actually.

**Comment by SaranshaM** [comment]
Okay  Sir thank you :)
