### ISSUE TITLE
problem about out of memory

### ISSUE THREAD

**Issue by sfqian** [wannier-berri/wannier-berri#339]
I calculated the ahc of a system with 152 wannier functions in a node with 64 cores and 256G memory. I encountered this problem :

symgroup : <wannierberri.symmetry.Group object at 0x2ae0506a2970>
processing 73644 K points : using  64 processes.
# K-points calculated  Wall time (sec)  Est. remaining (sec)
^[[2m^[[33m(raylet)^[[0m [2024-07-13 19:56:45,084 E 53927 53927] (raylet) node_manager.cc:3084: 1 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: f98b4716602ac622aad4382f3b0e62e91078bddbdea42b8931d8c7b4, IP: 172.100.1.14) over the last time period. To see more information about the Workers killed on this node, use `ray logs raylet.out -ip 172.100.1.14`

I am using this script to compute AHC:

import wannierberri as wberri
import pyfftw
import numpy as np
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'
os.environ['MKL_NUM_THREADS'] = '1'
os.environ['OMP_NUM_THREADS'] = '1'
system=wberri.System_w90('wannier90',berry=True, fft = "numpy")
grid=wberri.Grid(system,length=2001)
num_proc = 64
parallel=wberri.Parallel(num_cpus=num_proc)
Efermi=np.linspace(4.5, 5.5, 101)
wberri.run(system,
            grid=grid,
            calculators = {
                "ahc":wberri.calculators.static.AHC(Efermi=Efermi,tetra=False)
                          },
            parallel=parallel,
            parameters_K = dict( fftlib = "numpy" ),
            adpt_num_iter=10,
            fout_name='Fe',
            suffix = "run",
            restart=False,
            )

parallel.shutdown()

If I reduce the num_proc to 32, there will be no such problem. But the speed is also slower. Is there any other way to solve this problem?

**Comment by stepan-tsirkin** [comment]
Hi,

what is the FFT grid that is automatically created? usually, setting that grid manually helps to decrease memory consumption.

**Comment by sfqian** [comment]
Thanks for the reply. The fft grid is 10 7 7, Is the fft grid changed by setting NKFFT? Does reducing the fft grid affect the accuracy of results?

**Comment by stepan-tsirkin** [comment]
Ye, it can be set manua1
lly with the NKFFT parameterof the grid:
https://github.com/wannier-berri/wannier-berri/blob/5bfe6bd4151fa52656fb357616936aa4b290dcb5/wannierberri/grid/__grid.py#L60-L65

tChanging NKFFT should not change the results at all, if you do not use adaptive refinements. In fact, one can use NKFFT=[1,1,1], but that will loose the advantage of FFT, so a compromise between speed and memory should be chosen somwhere in the middle. 

With adaptive refinements, it does change the results (because its behaviour does depenf on NKFFT) , but it does not mean that they become less accurate, just a different value within the numerical error. 

Also, probably "tetra=False" will help converge with less k-points

Also, the number of k-points may be reduced by using  the symmetries:

https://github.com/wannier-berri/wannier-berri/blob/5bfe6bd4151fa52656fb357616936aa4b290dcb5/wannierberri/system/system.py#L95

**Comment by sfqian** [comment]
Thanks for the comment and advice. The problem has been solved.
