### ISSUE TITLE
Reading wannier90 system with guiding_centers = true can fail

### ISSUE THREAD

**Issue by jaemolihm** [wannier-berri/wannier-berri#93]
If `guiding_centers = true` is used in Wannier90, reading system with `transl_inv=True` can fail because the assert is False https://github.com/wannier-berri/wannier-berri/blob/9f2515fc0f55b33baecc88461f465a5b7de6ad05/wannierberri/__system_w90.py#L97-L101

The reason is that `chk.get_AA_q` does not use the guiding center method to calculate the Wannier centers, while the Wannier90 output (`wannier_centers_cart_auto`) is calculated using guiding centers.

(In most cases, guiding_centers does nothing, so the current implementation works. But there are some edge cases, like monolayers placed at the center of the supercell, that guiding_centers have significant effects. I attached an example.)

A simple workaround is just to trust the Wannier centers calculated by Wannier90, and overwrite the diagonals.
```python
if transl_inv:
    for iw in range(self.num_wann):
        self.AA_R[iw, iw, self.iR0, :] = self.wannier_centers_cart_auto[iw, :]
```

A complete fix will be to implement guiding centers in `__w90_files.py`, but I do not understand the theory of guiding centers so I cannot say whether it will be easy or not.

Reproducer (unzip and run `./run.sh`):
[input.zip](https://github.com/wannier-berri/wannier-berri/files/7553059/input.zip)

Wannier-Berri output:
```
[jmlim@im0 temp]$ ./wberri.py 
using fortio to read
Reading restart information from file BN.chk :
Time to read .chk : 0.015824317932128906
using ws_distance
irvec_new_all shape (43,)
time for ws_dist_map :  0.05253195762634277 0.023316383361816406 0.020260095596313477 0.007009744644165039 0.0019457340240478516
Time for MMN.__init__() : 0.0742490291595459 , read : 0.06488180160522461 , headstring 0.009367227554321289
Traceback (most recent call last):
  File "./wberri.py", line 3, in <module>
    system = wberri.System_w90('BN', berry=True, transl_inv=True)
  File "/group2/jmlim/shift_phase_convention/wannier-berri/wannierberri/__system_w90.py", line 101, in __init__
    wannier_centers_cart_new,self.wannier_centers_cart_auto-wannier_centers_cart_new))
AssertionError: the difference between read
[[ 1.2515 -0.7227  7.5003]
 [ 1.2515 -0.7226  7.5003]
 [ 1.2515 -0.8385  7.5003]
 [ 1.2515 -0.6032  7.5003]]
 and evluated 
[[ 1.2515e+00+0.j -7.2268e-01+0.j  4.7395e-10+0.j]
 [ 1.2515e+00+0.j -7.2256e-01+0.j -1.2500e+00+0.j]
 [ 1.2515e+00+0.j -8.3848e-01+0.j  8.3336e-01+0.j]
 [ 1.2515e+00+0.j -6.0317e-01+0.j -1.2500e+00+0.j]]
 wannier centers is 
[[-5.0069e-12+0.j  2.8912e-12+0.j  7.5003e+00+0.j]
 [-5.0069e-12+0.j  2.8907e-12+0.j  8.7503e+00+0.j]
 [-5.0069e-12+0.j  3.3399e-12+0.j  6.6669e+00+0.j]
 [-5.0067e-12+0.j  2.4308e-12+0.j  8.7503e+00+0.j]]
```

**Comment by stepan-tsirkin** [comment]
interesting, 
Is the simple workaround actually correct? do guiding centers modify only the diagonal part? If they also modify off-diagonal, it is better for a code to fail, than to produce incorrect results.

In any case, I am puzzled, I thought guiding_centers are used only during spread minimization.

Is the flag written in the chk, whether the guiding centers were used?

**Comment by jaemolihm** [comment]
> interesting, Is the simple workaround actually correct? do guiding centers modify only the diagonal part? If they also modify off-diagonal, it is better for a code to fail, than to produce incorrect results.

Yes, guiding centers modify only the diagonals.

> In any case, I am puzzled, I thought guiding_centers are used only during spread minimization.

They are used only during minimization, for the calculation of wannier centers and spreads.

> Is the flag written in the chk, whether the guiding centers were used?

It seems not, unfortunately.

https://github.com/wannier-developers/wannier90/blob/develop/src/w90chk2chk.F90

**Comment by jaemolihm** [comment]
After some thought, I think adding guiding centers flag in system_w90 and doing the workaround (and print some warning) if the flag is true is a good solution. As I said, one can always trust the centers computed by Wannier90.x.

In the long term, we can discuss with wannier90 developers to write guiding_centers flag to the chk file.

**Comment by stepan-tsirkin** [comment]
I agree with a workaround. Also, it the flag is False and the assertion fails, we can give a hint to set that flag to true.

I am afraid that the .chk being a binary, changing its format may affect any code that attempts to read it, also brings an issue of tracking different versions of the file. In principle, it should not be a problem if the flag does not add a new record to the file, but not sure. But you may discuss it on the w90 repository.

**Comment by stepan-tsirkin** [comment]
Look, as Nicola wrote 8 years [ago](https://lists.quantum-espresso.org/pipermail/wannier/2013-November/000726.html) ,,

> the idea is that if M_nn_kb was dispersionless, it would be identical
to b scalar rcenter, and (see eq 28 of the 2012 review) would give you 
rcenter. Since once the functions are maximally localized,
M_nn is optimally smooth as you surf the Brillouin zone, you want
to make sure that as you move around, the branch cuts are such that
M_nn gives you a Im ln M_nn that is roughly always b scalar rguide,
where rguide is an educated guess to rcenter.
>
> That info is still buried in the wann_phases subroutine inside 
wannierise.f90

In other words, when `transl_inv == True` the  wannier centers are defined using a imaginary part of logarithm, and we need to pick a proper branch. So, it is better to rely on the walues calculated by Wannier90 (actually always, if `transl_inv = True` we may just avoid the recalculation of wannier centers)  

What bothers me is that `postw90.x` does not use guiding centers, but just [recalculates](https://github.com/wannier-developers/wannier90/blob/528a67f8b38fceb2252f085877bb2ba9acece7fb/src/postw90/get_oper.F90#L450-L467) the values ignoring them (and in WannierBerri just reproduced this behavior) Does it mean that `postw90.x` goes wrong with guiding centers and `transl_inv = True` ? (the latter by default is `False` however) 

with `transl_inv=False` it is formally correct, because all `AA_R`s are treated equally, diagonal or non-diagonal. But there is some error which goes away in the limit  of dense ab-initio grid. However not sure if it is correct for the case of a slab centered in the unit cell center (rather than zero) and represented by a single k-point in that direction. However the question arises - are the off-diagonal position matrix elements correct in this case? because there is not `transl_inv` option for the off-diagonal elements.

A proper check would be to perform one calculation when the 2D material is centered at the origin of the unit cell, and another to place in the center. The results should match exactly in the  proper scheme, right?

Should we open an issue about it on the `Wannier90` repository?

**Comment by stepan-tsirkin** [comment]
@jaemolihm , actually there is already an [issue #378](https://github.com/wannier-developers/wannier90/issues/378) on Wannier90

**Comment by jaemolihm** [comment]
> @jaemolihm , actually there is already an [issue #378](https://github.com/wannier-developers/wannier90/issues/378) on Wannier90

Yes, and there is also https://github.com/wannier-developers/wannier90/issues/302 which is basically the same thing.

What you said are all correct, but my experience is that guiding_centers does not make much changes (i.e. the default branch choice is already good) when the WF spread is localized enough.
guiding_centers does make some changes

Regarding the comment you made in Wannier90 repository, my understanding of the issues in Wannier90 is not with `guiding_centers` but with `transl_inv`. So basically one can fix those issues by setting `transl_inv = true` in postw90.x run.
But I also agree that `guiding_centers` may become a problem e.g. in the case I reported in this issue. In such a case, your fix makes more sense.

> However not sure if it is correct for the case of a slab centered in the unit cell center (rather than zero) and represented by a single k-point in that direction. However the question arises - are the off-diagonal position matrix elements correct in this case?
> A proper check would be to perform one calculation when the 2D material is centered at the origin of the unit cell, and another to place in the center. The results should match exactly in the proper scheme, right?

I agree that the deeper problem is whether one can say which one of them is "better". I have some ideas and results on this, and I plan to write a paper on it.
